# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, commit-msg]
#exclude: (^|/)pyproject\.toml$|(^|/).pre-commit-full-config\.yaml|.pre-commit-config\.yaml$
repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.0
    hooks:
    - id: sqlfluff-fix
      additional_dependencies: ['dbt-snowflake==1.6.4', 'sqlfluff-templater-dbt']
      language: python
      args: [--ignore-local-config, --config=pyproject.toml]
      name: '---> [sqlfluff] fix '
    - id: sqlfluff-lint
      additional_dependencies: ['dbt-snowflake==1.6.4', 'sqlfluff-templater-dbt']
      args: [--ignore-local-config, --config=pyproject.toml]
      name: '---> [sqlfluff] lint '
